import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Gluten } from "next/font/google";
import "./globals.css";
import Nav from "@/app/components/Nav";
import * as React from "react";
import * as Popover from "@radix-ui/react-popover";

const gluten = Gluten({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={gluten.className}>
          {children}
          <Nav />
        </body>
      </html>
    </ClerkProvider>
  );
}
